### PR TITLE
Arbitrary objects are now signed

### PR DESCRIPTION
**Pull request by Scarzer**

### CODE REVIEW

**Comment by biancode** [comment]
for some complex structured objects a JSON.stringify is not enough for Node-RED to work with that msg in another Node-RED - for that is some to do to come from data to a working msg

**Comment by biancode** [comment]
Why should we hold the token in the msg later? With data it is separated and it is ready to send in the flow as the msg was. To accept your idea, the user should get an option to decide if it sends all in one or just msg, please.

**Comment by Scarzer** [comment]
I have limited experience with Node-RED. Would it be possible to be pointed towards some documentation that would help me build this up properly?

**Comment by biancode** [comment]
@Scarzer I am sorry but it is my experience, but there is no documentation for now. I'll work on it later and finish your request. Don't worry!

**Comment by biancode** [comment]
I bring your idea to the node ...

**Pull request closed without merging**
